Update README for "Use home-manager as a NixOS module"
Misterio77/nix-starter-configs pull request #34
Opened 2023-06-22 10:19 UTC by YanniPapandreou

As mentioned in issue #30 the README needs to be corrected to use home-manager as a NixOS module. I think this should be the correct instructions :)

2023-07-30 22:20 UTC, Misterio77 requested changes
Thanks a lot for contributing! Here's some nits before we merge it.

2023-07-30 22:20 UTC, Misterio77 commented on README.md
>        your-username = import ../home-manager;
I think it's okay to assume home-manager/home.nix, as this is how the repo is structured.

```suggestion
      your-username = import ../home-manager/home.nix;
```

2023-07-30 22:20 UTC, Misterio77 commented on README.md
> +
I think I will just go and add outputs to minimal as well, as it might be useful to people and it not having it is confusing, so we won't need this note.

```suggestion
```

2023-08-02 15:06 UTC, YanniPapandreou commented
@Misterio77 thanks a lot! I have committed your suggestions!

2023-08-19 11:37 UTC, Misterio77 commented
Sorry for taking so long! LGTM, thanks!

2023-08-19 11:37 UTC, merged