Some minor improvements
Misterio77/nix-starter-configs pull request #5
Opened 2022-10-20 20:10 UTC by ajgrf

1. Fixed a few misspellings.
2. Added `packages` output.
3. Use the same nixpkgs in `nix-shell` and `nix develop`. Unlikely to ever actually be a problem, but they should still be the same.

This should maybe be 3 separate PRs, but since they would each be so minor I didn't bother.

Finally, thanks for putting out such clear templates! I've been using flakes for over 2 years, but when I came across this repo recently I immediately refactored my own configs to more closely resemble your standard template. It helped me understand flakes better, and the result is much simpler and more organized.

2022-10-22 19:59 UTC, Misterio77 commented
Hey! Thanks for the contribution :)
The only nit would be that `packages` is supposed to be an attrset of packages, which nixpkgs is not; that's why it's exported as `legacyPackages`. It still works as expected, i.e. `nix run .#foo` will run `legacyPackages.system.foo`.

2022-10-22 20:00 UTC, Misterio77 requested changes

2022-10-22 20:00 UTC, Misterio77 commented on standard/flake.nix
> +
```suggestion
```

2022-10-22 20:20 UTC, ajgrf commented
OK, I was aware of the differences between `legacyPackages` and `packages`, but it almost seemed like separating the `pkgs` and `overlay` directories was done specifically to support including custom packages in both of them. Kind of like [exportPackages from flake-utils-plus](https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/lib/exportPackages.nix) but with a much simpler implementation.

Do you have a preference whether I delete that commit or add a new one to revert it?

2022-10-29 05:35 UTC, Misterio77 commented
Sorry for the delay!

> separating the pkgs and overlay directories was done specifically to support including custom packages in both of them

Both work for custom packages (`pkgs` are part of the `overlay` too), but the general idea is:
- If it's a program not packages that you'd like to use and export to the world, `pkgs`.
- If you're patching something, changing a version, or adding a package to a nixpkgs scope, `overlay`.
- `legacyPackages` exports nixpkgs with your overlays applied, usually for your own personal use
- `packages` is supposed to be very minimal and with just packages you'd like to publish to the world. Putting the nixpkgs set here makes it hard to discover actual new packages and breaks `nix flake check` (as nix expects `packages` to not have nested attrsets).

> Do you have a preference whether I delete that commit or add a new one to revert it?

Not at all! Both are fine :)

I'm merging this PR now, okay? Thanks for the contribution!

2022-10-29 05:36 UTC, Misterio77 approved these changes

2022-10-29 05:36 UTC, merged